version: '3'
services:
  node-server:
    build: ./server
    ports:
      - "3080:3080"
    container_name: learnWebAppsBackend
    environment:
      - DATABASE=postgres
      - DB_USER=prodUser
      - DB_PASSWORD=prodPW
      - DB_NAME=LearnWebappsProd
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - SESSION_KEY=${SESSION_KEY}
      - SQL_HOST=db
      - FRONTEND_URL=http://localhost:8080
      - SQL_PORT=5432
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    depends_on:
      - db
  vue-client:
    build: ./client
    ports:
      - "8080:8080"
    container_name: learnWebAppsFrontend
    environment:
      - BACKENDURL=http://localhost:3080
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    depends_on:
      - node-server
  db:
    image: postgres:11.0-alpine
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=prodUser
      - POSTGRES_PASSWORD=prodPW
      - POSTGRES_DB=LearnWebappsProd
    ports:
      - 5432:5432
volumes:
  postgres_data: