version: '3'
services:
  node-server:
    build: ./server
    ports:
      - "3080:3080"
    container_name: learnWebAppsBackend
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    depends_on:
      - db
  vue-client:
    build: ./client
    ports:
      - "8080:8080"
    container_name: learnWebAppsFrontend
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
  db:
    image: postgres:11.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=webAdmin
      - POSTGRES_PASSWORD=defaultPasswort
      - POSTGRES_DB=learnWebApps
volumes:
  postgres_data:
# prod file with nginx
# env Datei damit server db daten hat
# get data into node for db anbindung
# vue store, routes with user data