version: '3'
services:
  backend:
    build: ./server
    ports:
      - "3080:3080"
    container_name: learnWebAppsBackend
    environment:
      - DATABASE=postgres
      - DB_USER=webAdmin
      - DB_PASSWORD=defaultPasswort
      - DB_NAME=learnWebApps
      - DB_CONTAINER_NAME=learnWebAppsDB
      - SESSION_KEY=meinSecretKey
      - SQL_HOST=db
      - FRONTEND_URL=http://localhost
      - SQL_PORT=5432
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    depends_on:
      - db
  frontend:
    build: ./client
    ports:
      - "8080:8080"
    container_name: learnWebAppsFrontend
    environment:
      - BACKENDURL=http://localhost:3080
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    depends_on:
      - backend
  db:
    image: postgres:11.0-alpine
    container_name: learnWebAppsDB
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=webAdmin
      - POSTGRES_PASSWORD=defaultPasswort
      - POSTGRES_DB=learnWebApps
    ports:
      - 5432:5432
volumes:
  postgres_data: