version: '3'
services:
  node-server:
    build: ./server
    ports:
      - "3080:3080"
    container_name: learnWebAppsBackendProd
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    depends_on:
      - db
  vue-nginx-client:
    container_name: learnWebAppsFrontendProd
    build:
      context: ./client
      dockerfile: Dockerfile-prod
    ports:
      - '80:80'
  db:
    image: postgres:11.0-alpine
    container_name: learnWebAppsDBProd
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=webAdmin
      - POSTGRES_PASSWORD=defaultPasswort
      - POSTGRES_DB=learnWebApps
volumes:
  postgres_data:
# env Datei damit server db daten hat
# get data into node for db anbindung
# vue store, routes with user data
