name: Check_And_Deploy
on:
  push:

env:
  DB_CONTAINER_NAME: learnWebAppsDBProd
  SQL_USER: prodUser
  SQL_PW: prodPW
  DATABASE_NAME: LearnWebappsProd

jobs:
  buildAndPush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERPASSWORD }}

      - name: Build images
        run: docker-compose-prod.yml build

      - name: Push image
        if: github.ref == 'refs/heads/master'
        run: docker-compose-prod.yml push
